# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Ryan"
email = "99929x@gmail.com"
link = "https://github.com/ryanxin7"
avatar = "/images/avatar.png"