title = "Ryan's Notebook"
baseURL = "https://hg-xnlog.github.io/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
theme = "FixIt"

[params]
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    name ="文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false